# Generated by Django 5.2.1 on 2025-05-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIngreso', models.CharField(max_length=100)),
                ('idProducto', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
            ],
        ),
    ]
