# Generated by Django 5.2.1 on 2025-05-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.CharField(max_length=100)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('PresentacionProducto', models.CharField(max_length=100)),
                ('CantidadProductoblue', models.CharField(max_length=100)),
            ],
        ),
    ]
